// ERROR ACTIONS
export const RESET_ERRORS = 'RESET_ERRORS';

// EMAIL ACTIONS
export const FETCH_EMAILS_REQUEST = 'FETCH_EMAILS_REQUEST';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_FAILURE = 'FETCH_EMAILS_FAILURE';